[package]
name = "gslsys_multifit_nlinear"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
GSL-sys = "3.0.0"
rand = "0.8.5"
gslsyslib = { version = "0.1.0", path = "gslsyslib" }

[lib]
name = "rgsl_nlinear"
crate-type = ["dylib", "rlib"]
